  networks:
    paintwork:
  services:


    postgres:
      image: postgres:latest
      container_name: postgres_db
      networks:
        - paintwork
      restart: unless-stopped
      env_file:
        - ".env"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    backend:
      env_file:
      - .env
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      container_name: go_backend
      restart: unless-stopped
      
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      networks:
        - paintwork

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: node_frontend
      restart: unless-stopped
      depends_on:
        - backend
      ports:
        - "8081:8081" 
      environment:
        - NODE_ENV=production
      networks:
        - paintwork
    mongo:
      container_name: mongo_db
      image: mongo:latest
      restart: unless-stopped
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - paintwork
  volumes:
    postgres_data:
    mongo_data:
